{% set version = "3.11.0" %}

package:
  name: flit-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flit/flit-{{ version }}.tar.gz
  sha256: 58d0a07f684c315700c9c54a661a1130995798c3e495db0db53ce6e7d0121825
  folder: source

build:
  number: 0
  skip: true  # [py<36]

# Specifying `python` as a top-level build requirements to force conda to
# render the recipe correctly
requirements:
  host:
    - python

outputs:
  - name: flit-core
    version: {{ version }}
    build:
      script:
        # flit-core is a core python dependency and it used to bootstrap the whole packaging ecosystem.
        # Because of that, it cannot depend on anything except python itself.
        # We can't use pip because to build pip, we need setuptools and wheel. wheel requires flit-core.
        # So flit-core is "self-hosting" and provides its own build and install methods.
        - cd source/flit_core && {{ PYTHON }} -m flit_core.wheel
        - {{ PYTHON }} bootstrap_install.py dist/flit_core-{{ version }}-py3-none-any.whl
    requirements:
      host:
        - python
      run:
        - python
    test:
      imports:
        - flit_core
        - flit_core.common
      requires:
        - pip
      commands:
        - pip check
  # When building out the initial package set for a new Python version the
  # recommendation is to build flit-core first.
  <conda_recipe_manager.types.SentinelType object at 0x7fdc11760380>:  # If bootstrap: yes, build flit-core only; otherwise build all the outputs.
    - name: flit
    version: {{ version }}
    build:
      script_env:
        - FLIT_ROOT_INSTALL=1
      script:
        - cd source/ && {{ PYTHON }} -m flit install --deps=none
      entry_points:
        - flit = flit:main
    requirements:
      host:
        - python
        - pip
        - docutils
        - requests
        - tomli-w
        - {{ pin_subpackage('flit-core', exact=True) }}
      run:
        - python
        - pip  # pip may be executed with 'install' argument passed to flit
        - docutils
        - requests
        - tomli-w
        - {{ pin_subpackage('flit-core', exact=True) }}
    test:
      imports:
        - flit
        - flit.build
      requires:
        - pip
        - ripgrep
      commands:
        - pip check
        - flit --version | rg {{ version }}

about:
  home: https://flit.pypa.io/en/stable/
  license: BSD-3-Clause
  license_family: BSD
  license_file: source/LICENSE
  summary: Simplified packaging of Python modules
  description: |
    Flit is a simple way to put Python packages and modules on PyPI.
    It tries to require less thought about packaging and helps avoid
    common mistakes.
  dev_url: https://github.com/takluyver/flit
  doc_url: https://flit.pypa.io/en/latest/

extra:
  recipe-maintainers:
    - Carreau
    - minrk
    - takluyver
    - ocefpaf