{% set name = "flit" %}
{% set version = "1.0" %}
{% set wheel_tag = "py3" %}
{% set fn = "{}-{}-{}-none-any.whl".format(name, version, wheel_tag) %}
{% set sha256 = "5eba92b254f198e534855919c1596d68bb46a7ee2adab60037df6268672dba38" %}
{% set build = 1 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://pypi.io/packages/{{ wheel_tag }}/{{ name[0] }}/{{ name }}/{{ fn }}
  sha256: {{ sha256 }}

build:
  number: 0
  script: pip install --no-deps {{ fn }}
  skip: True  # [py2k]
  entry_points:
    - flit = flit:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - docutils
    - requests
    - requests_download
    - zipfile36  # [py<36]
    - pytoml
    - pip

test:
  imports:
    - flit
  commands:
    - flit --version

about:
  home: https://flit.readthedocs.io/
  license: BSD 3-clause
  license_family: BSD
  summary: Simplified packaging of Python modules

extra:
  recipe-maintainers:
    - Carreau
    - minrk
    - takluyver
