{% set version = "1.0" %}
{% set sha256 = "95b8577b2232da39ee14ae237575b7a85afeeabc1e87f4a19485fac34f85aa89" %}

package:
  name: flit
  version: {{ version }}

source:
  fn: flit-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/f/flit/flit-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m flit install --deps=none
  skip: True  # [py2k]
  entry_points:
    - flit = flit:main

requirements:
  build:
    - python
    - pip
    - docutils
    - requests
  run:
    - python
    - docutils
    - requests
    - requests_download
    - zipfile36  # [py<36]
    - pytoml
    - pip

test:
  imports:
    - flit
  commands:
    - flit --version

about:
  home: https://flit.readthedocs.io/
  license: BSD 3-clause
  license_family: BSD
  summary: Simplified packaging of Python modules

extra:
  recipe-maintainers:
    - Carreau
    - minrk
    - takluyver
