{% set version = "3.3.0" %}

package:
  name: flit-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flit/flit-{{ version }}.tar.gz
  sha256: 65fbe22aaa7f880b776b20814bd80b0afbf91d1f95b17235b608aa256325ce57
  folder: source

build:
  noarch: python
  number: 0

# Specifying `python` as a top-level build requirements to force conda to
# render the recipe correctly
requirements:
  host:
    - python

outputs:
  - name: flit-core
    version: {{ version }}
    build:
      script: python -m pip install --no-deps -vv source/flit_core/
      noarch: python
    requirements:
      host:
        - python
        - pip
      run:
        - python >=3.6
    test:
      imports:
        - flit_core
        - flit_core.common
      requires:
        - pip
        - python <3.10
      commands:
        - pip check

  - name: flit
    version: {{ version }}
    build:
      script: cd source/ && FLIT_ROOT_INSTALL=1 python -m flit install --deps=none
      noarch: python
      entry_points:
        - flit = flit:main
    requirements:
      host:
        - python
        - pip
        - docutils
        - requests
        - tomli
        - tomli-w
        - {{ pin_subpackage('flit-core', exact=True) }}
      run:
        - python >=3.6
        - pip
        - docutils
        - requests
        - tomli
        - tomli-w
        - {{ pin_subpackage('flit-core', exact=True) }}
    test:
      imports:
        - flit
      requires:
        - pip
        - python <3.10
      commands:
        - pip check
        - flit --version

about:
  home: https://flit.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: source/LICENSE
  summary: Simplified packaging of Python modules
  dev_url: https://github.com/takluyver/flit
  doc_url: https://flit.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - Carreau
    - minrk
    - takluyver
    - ocefpaf
