{% set version = "2.0.2" %}

package:
  name: flit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flit/flit-{{ version }}.tar.gz
  sha256: eb5f0b72aee1063426e4806f33bf603cd91a8b5d66bd8b76d009701c36607fec

build:
  number: 0
  skip: True  # [py2k]
  entry_points:
    - flit = flit:main

about:
  home: https://flit.readthedocs.io/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Simplified packaging of Python modules

extra:
  recipe-maintainers:
    - Carreau
    - minrk
    - takluyver
    - ocefpaf

outputs:
  - name: flit-core
    script: {{PYTHON}} -m pip install --no-deps flit_core/
    requirements:
      host:
        - python
        - pip
        - pytoml
      run:
        - python
        - pytoml
      test:
        imports:
          - flit_core

  - name: flit
    script: FLIT_ROOT_INSTALL=1 {{PYTHON}} -m flit install --deps=none  # [not win]
    script: {{PYTHON}} -m flit install --deps=none  # [win]
    requirements:
      host:
        - python
        - pip
        - docutils
        - requests
        - pytoml
        - zipfile36  # [py<36]
      run:
        - python
        - docutils
        - requests
        - requests_download
        - zipfile36  # [py<36]
        - pytoml
        - pip

    test:
      imports:
        - flit
      commands:
        - flit --version
