{% set version = "3.8.0" %}

package:
  name: flit-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flit/flit-{{ version }}.tar.gz
  sha256: d0f2a8f4bd45dc794befbf5839ecc0fd3830d65a57bd52b5997542fac5d5e937
  folder: source

build:
  number: 0
  skip: True  # [py<36]

# Specifying `python` as a top-level build requirements to force conda to
# render the recipe correctly
requirements:
  host:
    - python

outputs:
  - name: flit-core
    version: {{ version }}
    build:
      script: {{ PYTHON }} -m pip install --no-deps -vv source/flit_core/
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
    test:
      imports:
        - flit_core
        - flit_core.common
      requires:
        - pip
      commands:
        - pip check

  - name: flit
    version: {{ version }}
    build:
      script: cd source/ && FLIT_ROOT_INSTALL=1 python -m flit install --deps=none
      entry_points:
        - flit = flit:main
    requirements:
      host:
        - python
        - pip
        - docutils
        - requests
        - setuptools
        - tomli-w
        - wheel
        - {{ pin_subpackage('flit-core', exact=True) }}
      run:
        - python
        - docutils
        - requests
        - tomli-w
        - {{ pin_subpackage('flit-core', exact=True) }}
    test:
      imports:
        - flit
        - flit.build
      requires:
        - pip
      commands:
        - pip check
        - flit --version | grep -Fq {{ version }}

about:
  home: https://flit.pypa.io/en/stable/
  license: BSD-3-Clause
  license_family: BSD
  license_file: source/LICENSE
  summary: Simplified packaging of Python modules
  description: |
    Flit is a simple way to put Python packages and modules on PyPI. 
    It tries to require less thought about packaging and helps avoid 
    common mistakes. 
  dev_url: https://github.com/takluyver/flit
  doc_url: https://flit.pypa.io/en/latest/

extra:
  recipe-maintainers:
    - Carreau
    - minrk
    - takluyver
    - ocefpaf
