travis:
  secure:
    BINSTAR_TOKEN: TR4ZcdoqjxIJO3p+uOsNY0KhuKqu0U4mGRYv2Sl3Udq+dIJYQdRFSlgwBet3NBtOcEjVgMRtwrvnj1gsfYfoFHuby/tIzgg7uahv0rgCfP3FP6h9xIg51d0vKqoCXMDqUTVj+OuO/oVWHPUeKc9hW+D9mCnpZvzWR9VCFrED5JTWlPB7DutAPWnUgsx2qUjjvq3ksyDEp80DQJriXXiGA+4vqh7lkRKDNPQvdnLVxybkp8MY0CdUWBmzWIZ7EfViJSva2ba2hbacRCW8P3/c224Ej+4TS9Nwp2P3IeaesT6ojZ4kSTolNcA/XKZOrvVzVWtTRgMnfNQpO3QJ/F491gaDg7KoVhn1Cnr2iuwt3/X4S9A628jMq8W6no5P2ycPX5c1XaxFD8z7VAOsqXbQyNfrKsZN3lPdkIkyRna9KP+D8kBKDPdL8vHPvP+ocx78geAVAwa5YtdEcV0hFhEp0m10ae+W7+jmwRmoM4Y4hcTjFA1t5s2n/ecwVxnhU+YDKaUyr0bz+DlbvnkEU807jjnNrTxEVuuxHdzflXga/i1UvF3MTp+8s7lRd0Ag6RyLOYAST1Lcb0hgbWYtMZGk9cIj2/YF2HcZOqAzBkc149GPDaGKwSmGol4QuqTUM7Gtdoj/V65XfMWVUXxRI2A5NS8qhR7dXbALlEEnaF7PYFM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
